apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprodb
  labels:
    app: vprodb
spec:
  selector:
    matchLabels:
      app: vprodbpod
  replicas: 1
  template:
    metadata:
      name: db-pod
      labels:
        app: vprodbpod
    spec:
      containers:
        - name: dbpod
          image: bartlomiejrzekec/vprofiledb:v1
          ports:
            - name: db-port
              containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "vprodbpass"
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: db-volume
      nodeSelector:
        zone: eu-central-1a
      volumes:
        - name: db-volume
          hostPath:
            path: /home/vagrant/db-backup
            #type: Directory



