apiVersion: apps/v1
kind: Deployment
metadata:
  name: memcachedep
  labels:
    name: vpromemcache
spec:
  selector:
    matchLabels:
      name: vpromemcache
  replicas: 1
  template:
    metadata:
      labels:
        name: vpromemcache
    spec:
      containers:
        - name: memchachepod
          image: memcached
          ports:
            - name: memcacheport
              containerPort: 11211
