apiVersion: apps/v1
kind: Deployment
metadata:
  name: rmqdeployment
spec:
  selector:
    matchLabels:
      name: rabbitmqpod
  replicas: 1
  template:
    metadata:
      labels:
        name: rabbitmqpod
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq
          ports:
            - name: rmqport
              containerPort: 15672
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "guest"
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: rmq-pass