apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprodep
spec:
  selector:
    matchLabels:
      name: vpropod
  replicas: 1
  template:
    metadata:
      labels:
        name: vpropod
    spec:
      containers:
        - name: vproapp
          image: bartlomiejrzekec/vprofileapp:v1
          ports:
            - containerPort: 8080
      initContainers:
        - name: init-mydb
          image: busybox
          command: ["sh", "-c", "until nslookup vprodb; do echo Waiting for db service; sleep 2; done;"]
        - name: init-memcache
          image: busybox
          command: ["sh", "-c", "until nslookup vprocache01; do echo Waiting for memchache service; sleep 2; done;"]
